modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="tbbm"
version="${file.jarVersion}"
displayName="Blocks Mod"
logoFile="examplemod.png"
credits="To the team that helped create the mod"
authors="PurplePineapple, WynnKunGz, Shadow"
description='''
Adds the blocks for the modpack we are making
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
