modLoader="javafml"
loaderVersion="[36,)"
license="BSD 3-Clause License"

[[mods]]
modId="tbbm"
version="1.0.0"
displayName="Blocks Mod"
logoFile="examplemod.png"
credits="To the team that helped create the mod"
authors="PurplePineapple, WynnKunGz, Shadow, RealYusufIsmail"
description='''
Adds the blocks for the modpack we are making
'''

[[dependencies.tbbm]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.tbbm]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
